# 2강. 파이썬
## 2.3 넘파이

### 2.3.1 여러 가지 함수

In [1]:
import numpy as np

a = np.array([1, 5, 0, -1])
b = np.ones((2, 2, 2))
c = np.zeros((2, 3))
d = np.arange(10)
e = np.linspace(0, 10, 5)
f = np.random.randint(2, 10, 5)

a

array([ 1,  5,  0, -1])

In [2]:
print("a: ", a)
print("b: ", b)
print("c: ", c)
print("d: ", d)
print("e: ", e)
print("f: ", f)

a:  [ 1  5  0 -1]
b:  [[[1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]]]
c:  [[0. 0. 0.]
 [0. 0. 0.]]
d:  [0 1 2 3 4 5 6 7 8 9]
e:  [ 0.   2.5  5.   7.5 10. ]
f:  [9 3 4 8 8]


In [3]:
c.shape

(2, 3)

In [4]:
len(c)

2

In [5]:
c.ndim

2

In [6]:
c.dtype

dtype('float64')

In [7]:
c.reshape(1,6)

array([[0., 0., 0., 0., 0., 0.]])

In [8]:
c.astype('int')

array([[0, 0, 0],
       [0, 0, 0]])

In [9]:
d.shape

(10,)

In [10]:
d1 = d.reshape(2,5)
d1

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [11]:
d1.shape

(2, 5)

In [12]:
d1.ravel()

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

### 2.3.2 배열의 인덱싱

In [13]:
d1[0]

array([0, 1, 2, 3, 4])

In [14]:
d1[1]

array([5, 6, 7, 8, 9])

In [15]:
d1[0, 2]

2

In [16]:
d1[0, 2:4]

array([2, 3])

In [17]:
d1[-1,3]

8

In [18]:
# 조건문을 이용한 인덱스 검색
mu = 0
sigma = 1
arr = np.random.normal(mu, sigma, (5,3))
arr

array([[-2.14944495, -0.41344988, -0.23961872],
       [-0.50379382,  1.43850641, -0.98221018],
       [ 0.24135264, -0.65075032,  0.4342283 ],
       [-0.19442202, -0.43991385,  1.19718222],
       [-2.21901767,  1.71148841,  0.22396392]])

In [19]:
np.where(abs(arr) > sigma, "out", "in")

array([['out', 'in', 'in'],
       ['in', 'out', 'in'],
       ['in', 'in', 'in'],
       ['in', 'in', 'out'],
       ['out', 'out', 'in']], dtype='<U3')

In [20]:
np.where(abs(arr) > sigma)

(array([0, 1, 3, 4, 4]), array([0, 1, 2, 0, 1]))

### 2.3.3 배열의 기본 연산

In [21]:
a = np.array([[1, 3], [0, -1]])
b = np.random.randint(0, 10, 4).reshape(2, 2)

In [22]:
a+b

array([[10,  3],
       [ 0, -1]])

In [23]:
a*b

array([[9, 0],
       [0, 0]])

In [24]:
a**b

array([[1, 1],
       [1, 1]])

In [25]:
2*a

array([[ 2,  6],
       [ 0, -2]])

In [26]:
a-1

array([[ 0,  2],
       [-1, -2]])

In [27]:
np.matmul(a, b)

array([[9, 0],
       [0, 0]])

### 2.3.4 배열의 병합

In [28]:
np.concatenate([a, b], axis=0)

array([[ 1,  3],
       [ 0, -1],
       [ 9,  0],
       [ 0,  0]])

In [29]:
np.vstack((a,b))

array([[ 1,  3],
       [ 0, -1],
       [ 9,  0],
       [ 0,  0]])

In [30]:
np.concatenate([a, b], axis=1)

array([[ 1,  3,  9,  0],
       [ 0, -1,  0,  0]])

In [31]:
np.hstack((a,b))

array([[ 1,  3,  9,  0],
       [ 0, -1,  0,  0]])

### 2.3.5 다양한 함수

In [32]:
des = [np.sum(a), np.mean(a), np.std(a), np.max(a), np.min(a)]
print(des)

[3, 0.75, 1.479019945774904, 3, -1]
