In [2]:
import torch
print(torch.tensor([[1,2],[3,4]]))

tensor([[1, 2],
        [3, 4]])


In [3]:
print(torch.tensor([[1,2],[3,4]], device="cuda:0"))

tensor([[1, 2],
        [3, 4]], device='cuda:0')


In [4]:
print(torch.tensor([[1,2],[3,4]], dtype=torch.float64))

tensor([[1., 2.],
        [3., 4.]], dtype=torch.float64)


In [7]:
import numpy as np
x =np.array([[1,2],[3,4]])
print(x, type(x))

x = torch.from_numpy(x)
print(x, type(x))

x = x.numpy()
print(x, type(x))

[[1 2]
 [3 4]] <class 'numpy.ndarray'>
tensor([[1, 2],
        [3, 4]]) <class 'torch.Tensor'>
[[1 2]
 [3 4]] <class 'numpy.ndarray'>


In [8]:
temp = torch.tensor([[1,2],[3,4]], device="cuda:0")
print(temp.cpu().numpy())

[[1 2]
 [3 4]]


In [15]:
x2 = torch.FloatTensor([[[1,2],[3,4]], # [0,,]
                        [[5,6],[7,8]], # [1,,]
                        [[9,10],[11,12]] # [2,,]
                        ])
print(x2)
print(x2.size())
print(x2.shape)
print(x2.dim())
print(x2[1][0][1])
print(x2[1])

tensor([[[ 1.,  2.],
         [ 3.,  4.]],

        [[ 5.,  6.],
         [ 7.,  8.]],

        [[ 9., 10.],
         [11., 12.]]])
torch.Size([3, 2, 2])
torch.Size([3, 2, 2])
3
tensor(6.)
tensor([[5., 6.],
        [7., 8.]])


In [16]:
x3 = torch.FloatTensor([
    [1,2],
    [3,4]])
print(x3.sum())
print(x3.mean())
print(x3.sum(dim=0))
print(x3.sum(dim=1))

tensor(10.)
tensor(2.5000)
tensor([4., 6.])
tensor([3., 7.])


In [17]:
x4 = torch.FloatTensor([
    [1,2],
    [3,4]])
y = 1
z = x4 + y
print(z)

tensor([[2., 3.],
        [4., 5.]])


In [18]:
x5 = torch.FloatTensor([
    [1,2],
    [3,4]])
y2 = torch.FloatTensor(
    [1,2])
print(x5.size(), y2.size())
print(x5 + y2)

torch.Size([2, 2]) torch.Size([2])
tensor([[2., 4.],
        [4., 6.]])


In [19]:
x6 = torch.FloatTensor(
    [[1,2]])
y2 = torch.FloatTensor(
    [[3],
     [5]])
print(x6.size(), y2.size())
print(x6 + y2)

torch.Size([1, 2]) torch.Size([2, 1])
tensor([[4., 5.],
        [6., 7.]])


In [23]:
x7 = torch.FloatTensor([[[1, 2],
 [3, 4]],
 [[5, 6],
 [7, 8]],
 [[9, 10],
 [11, 12]]])
print(x7.size()) # torch.Size([3, 2, 2]) -> 3 x 2 x 2 = 12개
print(x7.view([-1,3])) # 원래 갯수를 맞춰 주는 역할 : -1 -> 4
print(x7.view([-1,3]).size())

torch.Size([3, 2, 2])
tensor([[ 1.,  2.,  3.,  4.],
        [ 5.,  6.,  7.,  8.],
        [ 9., 10., 11., 12.]])
torch.Size([3, 4])


In [25]:
print(x7.view(3,4))
print(x7.view(3,1,4))
print(x7.view(-1))
print(x7.view(3, -1))
print(x7.view(-1,1,4))
print(x7.view(3,2,2,-1))

tensor([[ 1.,  2.,  3.,  4.],
        [ 5.,  6.,  7.,  8.],
        [ 9., 10., 11., 12.]])
tensor([[[ 1.,  2.,  3.,  4.]],

        [[ 5.,  6.,  7.,  8.]],

        [[ 9., 10., 11., 12.]]])
tensor([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12.])
tensor([[ 1.,  2.,  3.,  4.],
        [ 5.,  6.,  7.,  8.],
        [ 9., 10., 11., 12.]])
tensor([[[ 1.,  2.,  3.,  4.]],

        [[ 5.,  6.,  7.,  8.]],

        [[ 9., 10., 11., 12.]]])
tensor([[[[ 1.],
          [ 2.]],

         [[ 3.],
          [ 4.]]],


        [[[ 5.],
          [ 6.]],

         [[ 7.],
          [ 8.]]],


        [[[ 9.],
          [10.]],

         [[11.],
          [12.]]]])


In [26]:
print(x7.reshape(3,4))
print(x7.reshape(3,1,4))
print(x7.reshape(-1))
print(x7.reshape(3, -1))
print(x7.reshape(-1,1,4))
print(x7.reshape(3,2,2,1))

tensor([[ 1.,  2.,  3.,  4.],
        [ 5.,  6.,  7.,  8.],
        [ 9., 10., 11., 12.]])
tensor([[[ 1.,  2.,  3.,  4.]],

        [[ 5.,  6.,  7.,  8.]],

        [[ 9., 10., 11., 12.]]])
tensor([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12.])
tensor([[ 1.,  2.,  3.,  4.],
        [ 5.,  6.,  7.,  8.],
        [ 9., 10., 11., 12.]])
tensor([[[ 1.,  2.,  3.,  4.]],

        [[ 5.,  6.,  7.,  8.]],

        [[ 9., 10., 11., 12.]]])
tensor([[[[ 1.],
          [ 2.]],

         [[ 3.],
          [ 4.]]],


        [[[ 5.],
          [ 6.]],

         [[ 7.],
          [ 8.]]],


        [[[ 9.],
          [10.]],

         [[11.],
          [12.]]]])


In [29]:
x = torch.FloatTensor([[[1, 2], [3, 4]]])
print(1,x.size())  #결과 : torch.Size([1, 2, 2])
print(2, x.squeeze())
print(3, x.squeeze().size())
print(4, x.squeeze(0))
print(5, x.squeeze(0).size())
print(6, x.squeeze(1))
print(7, x.squeeze(1).size())

1 torch.Size([1, 2, 2])
2 tensor([[1., 2.],
        [3., 4.]])
3 torch.Size([2, 2])
4 tensor([[1., 2.],
        [3., 4.]])
5 torch.Size([2, 2])
6 tensor([[[1., 2.],
         [3., 4.]]])
7 torch.Size([1, 2, 2])


In [30]:
# x.unsqueeze(0), 0행 차원을 추가, 1 열 차원을 추가.
x = torch.FloatTensor([[1, 2],[3, 4]])
print(x.size()) # 결과 : torch.Size([2, 2])
print(x.unsqueeze(2)) # 3차원 2,2,1
print(x.unsqueeze(-1)) # 3차원 2,2,1
print(x.reshape(2, 2, -1)) # 3차원 2,2,1
# 이미지 의 각 픽섹의 단위를 맞추기 위해서,
# RGB , 3채널 -> 3차원 ,


torch.Size([2, 2])
tensor([[[1.],
         [2.]],

        [[3.],
         [4.]]])
tensor([[[1.],
         [2.]],

        [[3.],
         [4.]]])
tensor([[[1.],
         [2.]],

        [[3.],
         [4.]]])


In [35]:
x = torch.FloatTensor([
    [[1, 2],
    [3, 4]],

    [[5, 6],
    [7, 8]],

 [[9, 10],
 [11, 12]]])
print(x.size())
# 결과: torch.Size([3, 2, 2]

print(1,x[0])
print(2,x[0, :])
print(3,x[0, :, :])
print("===============================")
print(4,x[-1])
print(5,x[-1, :])
print("===============================")
print(6,x[-1, :, :])
print(7,x[:, 0, :])
print("===============================")
print(8_1,x[1:3, :, :])
print(8_2,x[1:3, :, :].size())
print(9_1,x[:, :1, :])
print(9_2,x[:, :1, :].size())
print(10,x[:, :-1, :].size())

torch.Size([3, 2, 2])
1 tensor([[1., 2.],
        [3., 4.]])
2 tensor([[1., 2.],
        [3., 4.]])
3 tensor([[1., 2.],
        [3., 4.]])
4 tensor([[ 9., 10.],
        [11., 12.]])
5 tensor([[ 9., 10.],
        [11., 12.]])
6 tensor([[ 9., 10.],
        [11., 12.]])
7 tensor([[ 1.,  2.],
        [ 5.,  6.],
        [ 9., 10.]])
81 tensor([[[ 5.,  6.],
         [ 7.,  8.]],

        [[ 9., 10.],
         [11., 12.]]])
82 torch.Size([2, 2, 2])
91 tensor([[[ 1.,  2.]],

        [[ 5.,  6.]],

        [[ 9., 10.]]])
92 torch.Size([3, 1, 2])
10 torch.Size([3, 1, 2])


In [39]:
x = torch.FloatTensor(13, 4)
splits = x.split(4, dim=0)
for s in splits:
 print(s.size())


torch.Size([4, 4])
torch.Size([4, 4])
torch.Size([4, 4])
torch.Size([1, 4])


In [41]:
 # 균등하게 나눈다.
 x = torch.FloatTensor(13, 4)
 chunks = x.chunk(3, dim=0)
 for c in chunks:
  print(c.size())

torch.Size([5, 4])
torch.Size([5, 4])
torch.Size([3, 4])


In [42]:
x = torch.FloatTensor([[[1, 1],
 [2, 2]],

 [[3, 3],
 [4, 4]],

 [[5, 5],
 [6, 6]]])
#index_select 는 특정 인덱스를 기준으로 텐서에서 요소를 선택하는데 사용함.
# dim=0 -> 행을 기준으로
# 인덱스 2번 : 3번째   인덱스 1번 : 2번째
indice= torch.LongTensor([2, 1])
print(x.size())
y = x.index_select(dim=0, index=indice)
print(y)
print(y.size())

torch.Size([3, 2, 2])
tensor([[[5., 5.],
         [6., 6.]],

        [[3., 3.],
         [4., 4.]]])
torch.Size([2, 2, 2])


In [43]:
x = torch.FloatTensor([[1, 2, 3],
 [4, 5, 6],
 [7, 8, 9]])
y = torch.FloatTensor([[10, 11, 12],
 [13, 14, 15],
 [16, 17, 18]])
print(x.size(), y.size())

z = torch.cat([x, y], dim=0)
print(z)
print(z.size())

z = torch.cat([x, y], dim=-1)
print(z)
print(z.size())

torch.Size([3, 3]) torch.Size([3, 3])
tensor([[ 1.,  2.,  3.],
        [ 4.,  5.,  6.],
        [ 7.,  8.,  9.],
        [10., 11., 12.],
        [13., 14., 15.],
        [16., 17., 18.]])
torch.Size([6, 3])
tensor([[ 1.,  2.,  3., 10., 11., 12.],
        [ 4.,  5.,  6., 13., 14., 15.],
        [ 7.,  8.,  9., 16., 17., 18.]])
torch.Size([3, 6])


In [45]:
x = torch.FloatTensor([[1, 2, 3],
 [4, 5, 6],
 [7, 8, 9]])
y = torch.FloatTensor([[10, 11, 12],
 [13, 14, 15],
 [16, 17, 18]])

z = torch.stack([x, y])
print(z)
print(z.size())

z = torch.stack([x, y], dim=-1)
print(z)
print(z.size())

tensor([[[ 1.,  2.,  3.],
         [ 4.,  5.,  6.],
         [ 7.,  8.,  9.]],

        [[10., 11., 12.],
         [13., 14., 15.],
         [16., 17., 18.]]])
torch.Size([2, 3, 3])
tensor([[[ 1., 10.],
         [ 2., 11.],
         [ 3., 12.]],

        [[ 4., 13.],
         [ 5., 14.],
         [ 6., 15.]],

        [[ 7., 16.],
         [ 8., 17.],
         [ 9., 18.]]])
torch.Size([3, 3, 2])


In [49]:
x = torch.FloatTensor([[1, 2, 3],
 [4, 5, 6],
 [7, 8, 9]]) # 3x3
y = torch.FloatTensor([[10, 11, 12],
 [13, 14, 15],
 [16, 17, 18]]) # 3x3

# z = torch.stack([x, y])
print(x.unsqueeze(0)) # 1x3x3
print(x.unsqueeze(0).size())

print(y.unsqueeze(0))  # 1x3x3
print(y.unsqueeze(0).size())

print(x.unsqueeze(1))
print(x.unsqueeze(1).size())

print(y.unsqueeze(1))
print(y.unsqueeze(1).size())

print(x.unsqueeze(2))
print(x.unsqueeze(2).size())

print(y.unsqueeze(2))
print(y.unsqueeze(2).size())

z = torch.cat([x.unsqueeze(0), y.unsqueeze(0)], dim=0)
print(z)
print(z.size())

tensor([[[1., 2., 3.],
         [4., 5., 6.],
         [7., 8., 9.]]])
torch.Size([1, 3, 3])
tensor([[[10., 11., 12.],
         [13., 14., 15.],
         [16., 17., 18.]]])
torch.Size([1, 3, 3])
tensor([[[1., 2., 3.]],

        [[4., 5., 6.]],

        [[7., 8., 9.]]])
torch.Size([3, 1, 3])
tensor([[[10., 11., 12.]],

        [[13., 14., 15.]],

        [[16., 17., 18.]]])
torch.Size([3, 1, 3])
tensor([[[1.],
         [2.],
         [3.]],

        [[4.],
         [5.],
         [6.]],

        [[7.],
         [8.],
         [9.]]])
torch.Size([3, 3, 1])
tensor([[[10.],
         [11.],
         [12.]],

        [[13.],
         [14.],
         [15.]],

        [[16.],
         [17.],
         [18.]]])
torch.Size([3, 3, 1])
tensor([[[ 1.,  2.,  3.],
         [ 4.,  5.,  6.],
         [ 7.,  8.,  9.]],

        [[10., 11., 12.],
         [13., 14., 15.],
         [16., 17., 18.]]])
torch.Size([2, 3, 3])


In [53]:
x=torch.randperm(10) #
print(x)
print(x.size())

tensor([4, 2, 6, 3, 9, 7, 8, 5, 0, 1])
torch.Size([10])


In [56]:
# 0 ~ 26 : 0 <= x < 27, 랜덤하게 나열해준다. = 순열
x=torch.randperm(3**3).reshape(3,3,-1) # 3차원의 텐서 형태
print(x)
print(x.size())

tensor([[[18, 16,  4],
         [10,  0, 22],
         [26, 20,  7]],

        [[ 8,  2, 13],
         [17, 21,  1],
         [ 3,  6, 25]],

        [[15,  9, 12],
         [23,  5, 14],
         [19, 11, 24]]])
torch.Size([3, 3, 3])


In [57]:
print(torch.ones(2,3))
print(torch.zeros(2,3))
x=torch.FloatTensor([[1,2,3],[4,5,6]])
print(x)
print(x.size())
print(torch.ones_like(x))
print(torch.zeros_like(x))

tensor([[1., 1., 1.],
        [1., 1., 1.]])
tensor([[0., 0., 0.],
        [0., 0., 0.]])
tensor([[1., 2., 3.],
        [4., 5., 6.]])
torch.Size([2, 3])
tensor([[1., 1., 1.],
        [1., 1., 1.]])
tensor([[0., 0., 0.],
        [0., 0., 0.]])
